services:
  youtvfetcher:
    image: stefanscherer/youtvfetcher:hd-hq
    container_name: youtvfetcher
    restart: always
    volumes:
      - './youtvfetcher/.youtvfetcher.json:/root/.youtvfetcher.json'
      - "/srv/dev-disk-by-uuid-a403cd9c-cf83-44c8-92dd-45769f088b6b/stefan/Movies/:/videos/"
    working_dir: '/videos'

  stefan-daapd:
    image: linuxserver/daapd:28.9.20240214
    container_name: stefan-daapd
    restart: always
    volumes:
      - "/srv/dev-disk-by-uuid-a403cd9c-cf83-44c8-92dd-45769f088b6b/familie/Music/:/media/"
      - './data/stefan-daapd/cache/:/cache/'
      - './data/stefan-daapd/remote/:/remote/'
      - './stefan-daapd/:/config/'
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Berlin
    # ports:
    #   - 3789:3789

  unifi:
    image: jacobalberty/unifi:v8.0.28
    container_name: unifi
    restart: unless-stopped
    volumes:
      - './data/unifi/:/unifi/'
    environment:
      - TZ=Europe/Berlin
    user: unifi
    ports:
      - 8080:8080
      - 8443:8443
      - 3478:3478/udp

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.02.0
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9090:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
    dns:
      - 127.0.0.1
      - 192.168.1.1
      - 1.1.1.1
    volumes:
      - ./data/pihole/etc/:/etc/pihole/
      - ./data/pihole/dnsmasq.d/:/etc/dnsmasq.d/
      - ./data/pihole/pihole.log:/var/log/pihole.log
    cap_add:
      - NET_ADMIN

  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    ports:
      - 9000:9000
      # - 9443:9443
