version: '3.5'

volumes:
  videos:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.110
      device: ":/nfs/Public/Shared Videos/Carina"

services:
  daapd:
    # build: forked-daapd
    image: stefanscherer/rpi-forked-daapd:25.0
    restart: always
    volumes:
      - './music:/media'
      - './data/forked-daapd/cache:/cache'
      - './data/forked-daapd/remote:/remote'
    network_mode: host
    expose:
      - 3689
    ports:
      - 3689:3689

  youtvfetcher:
    image: stefanscherer/youtvfetcher:latest
    restart: always
    volumes:
      - './youtvfetcher/.youtvfetcher.json:/root/.youtvfetcher.json'
      - "videos:/videos/"
    working_dir: '/videos'

  portainer:
    image: portainer/portainer:1.20.1
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    expose:
      - 9000
    ports:
      - 80:9000

  samba:
    # build: samba
    image: stefanscherer/rpi-samba:4.7.6
    hostname: 'pi128'
    restart: always
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    volumes:
      - './data/samba:/share/scanner'
    command: -s "Scanner:/share/scanner:rw:"
