version: '3.5'

volumes:
  videos:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.110
      device: ":/nfs/Public/Shared Videos/Carina"

services:
  daapd: # build: forked-daapd
    image: stefanscherer/rpi-forked-daapd:25.0
    restart: always
    volumes:
      - './music:/media'
      - './data/forked-daapd/cache:/cache'
      - './data/forked-daapd/remote:/remote'
      - './forked-daapd/forked-daapd.conf:/etc/forked-daapd.conf'
    network_mode: host
    expose:
      - 3689
    ports:
      - 3689:3689

  papa-daapd:
    # build: forked-daapd
    image: stefanscherer/rpi-forked-daapd:25.0
    restart: always
    volumes:
      - './music:/media'
      - './data/papa-daapd/cache:/cache'
      - './data/papa-daapd/remote:/remote'
      - './papa-daapd/forked-daapd.conf:/etc/forked-daapd.conf'
    network_mode: host
    expose:
      - 3789
    ports:
      - 3789:3789

  youtvfetcher:
    image: stefanscherer/youtvfetcher:latest
    restart: always
    volumes:
      - './youtvfetcher/.youtvfetcher.json:/root/.youtvfetcher.json'
      - "videos:/videos/"
    working_dir: '/videos'

  portainer:
    image: portainer/portainer:1.20.1
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    expose:
      - 9000
    ports:
      - 80:9000

  samba:
    # build: samba
    image: stefanscherer/rpi-samba:4.7.6
    hostname: 'pi128'
    restart: always
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    volumes:
      - './data/samba:/share/scanner'
      - './music:/share/music'
    command: -s "Scanner:/share/scanner:rw:" -s "Music:/share/music:rw:"

  pihole:
    container_name: pihole
    image: pihole/pihole:v4.4
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
    dns:
      - 127.0.0.1
      - 192.168.1.1
      - 1.1.1.1
    volumes:
      - ./pihole/etc/:/etc/pihole/
      - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
      - ./pihole/pihole.log:/var/log/pihole.log
    cap_add:
      - NET_ADMIN
