#!/bin/sh

mkdir -p /log/forked-daapd /cache/forked-daapd

/etc/init.d/dbus start
/usr/sbin/avahi-daemon --no-chroot -D
/usr/sbin/forked-daapd -f -c /etc/forked-daapd.conf
/usr/sbin/avahi-daemon -k
/etc/init.d/dbus stop
