#!/bin/sh

mkdir -p /log/forked-daapd /cache/forked-daapd

/etc/init.d/dbus start
#/etc/init.d/avahi-daemon start
/usr/sbin/forked-daapd -f -c /etc/forked-daapd.conf
#/etc/init.d/avahi-daemon stop
/etc/init.d/dbus stop
